// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/21/2024, 3:34:03 PM
const configMerger = require("/home/drake/code/web_dev/vue/cis115-vue-example/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/drake/code/web_dev/vue/cis115-vue-example/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/drake/code/web_dev/vue/cis115-vue-example/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/drake/code/web_dev/vue/cis115-vue-example/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/drake/code/web_dev/vue/cis115-vue-example/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/drake/code/web_dev/vue/cis115-vue-example/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/drake/code/web_dev/vue/cis115-vue-example/plugins/**/*.{js,ts,mjs}","/home/drake/code/web_dev/vue/cis115-vue-example/composables/**/*.{js,ts,mjs}","/home/drake/code/web_dev/vue/cis115-vue-example/utils/**/*.{js,ts,mjs}","/home/drake/code/web_dev/vue/cis115-vue-example/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/drake/code/web_dev/vue/cis115-vue-example/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/drake/code/web_dev/vue/cis115-vue-example/app.config.{js,ts,mjs}"] } }));

module.exports = config
